owner: yourepo
repo: upptime
sites:
  - name: YouRepo
    url: https://www.yourepo.com
    icon: https://www.yourepo.com/favicon.ico

status-website:
  cname: status.yourepo.com
  logoUrl: https://www.yourepo.com/CydiaIcon.png
  themeUrl: https://status.yourepo.com/adaptative.css
  favicon: https://www.yourepo.com/favicon.ico
  name: YouRepo Status
  introTitle: "**YouRepo** Live Status."
  introMessage: Real-time status and performance metrics page for YouRepo.
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: YouRepo
      href: https://www.yourepo.com/
