owner: yourepo
repo: upptime
sites:
  - name: YouRepo Website
    url: https://www.yourepo.com/
    icon: https://www.yourepo.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
  - name: YouRepo API
    url: https://api.yourepo.com/1.0/application/usage.json?secret_key=$API_SECRET_KEY
    icon: https://www.yourepo.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201

status-website:
  cname: status.yourepo.com
  logoUrl: https://www.yourepo.com/CydiaIcon.png
  favicon: https://www.yourepo.com/favicon.ico
  name: "YouRepo Status"
  introTitle: "**YouRepo** Live Status."
  introMessage: "Real-time status and performance metrics page for YouRepo."
  metaTags:
    - name: robots
      content: noindex
  links:
    - rel: stylesheet
      href: https://status.yourepo.com/themes/night.css
      media: "(prefers-color-scheme: dark)"
  navbar:
    - title: Status
      href: /
    - title: YouRepo
      href: https://www.yourepo.com/
